; Legacy Teensy 4.1/CAN build.
[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy@5.2.0
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra -Wpedantic -Werror=return-type
lib_deps =
    https://github.com/odriverobotics/ODriveArduino.git#f52eef5d72d65c64f4853b55fd31626dec52eafd
    https://github.com/tonton81/FlexCAN_T4.git#b928bcb2f74fdf0ccb76660f52ca1a2819ff4e2c
    https://github.com/PaulStoffregen/Encoder.git#c083e9cbd6400f7e72a794c0d371a00a09d2a25d

[env:native]
platform = native
test_framework = unity
test_build_src = false
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
